### ISSUE TITLE
Search and Delete operation are not working in this project for student and books details window 

### ISSUE THREAD

**Issue by Aniketshitole** [kunaltyagi9/Library-Management-System#1]
Search and Delete operation are not working in this project for student and books details window. 
Can you please solve this problem and update us and please can you share the documentation and digrams if you have 
 ![issue](https://user-images.githubusercontent.com/43912663/113517641-dc665f00-959e-11eb-89ab-5cfdf043856f.PNG)

**Comment by kunaltyagi9** [comment]
This part of the project is incomplete, I have not handled functionality of Search and Delete buttons.
Instead of raising an issue, you could have checked that as well by going through the code
